global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'log-service'
    static_configs:
      - targets: ['log-service:8080']
        labels:
          service: 'log-service'
          environment: 'development'
